Add CMake support
jtsiomb/c11threads pull request #23
Opened 2023-01-21 19:53 UTC by oold

This will allow for a smoother initialization on Win32 by doing that work on DLL load. I've also taken this opportunity to remove the special, public, Win32-specific functions and I've reworked the list structures. The VS files were removed as they can now be generated via CMake.

Bonus: The CMake support can also be used for other targets and will simply add the `include` directory.

2023-01-22 04:59 UTC, jtsiomb requested changes
Unless I'm misunderstanding, there are some code improvements, AND the addition of a cmake build file in this pull request. I want the additions, while I'm not decided on cmake. Please split this into two separate pull requests.

2023-01-22 04:59 UTC, jtsiomb commented on README.md
> +Simply add the CMake project to your own project or build a shared library from
I don't like the cmake-specific wording. I prefer instructing people to compile `c11threads_win32.c`, and leave them to do it with whatever build system they choose to.

If there is some valueable advice for cmake users, it should be less prominent, in the form of "if you use cmake, you can do X Y and Z", but if it's not some arcane knowledge we're talking about, and it's plain enough what needs to be done, I'd rather leave it at the build-system agnostic instructions.

2023-01-22 04:59 UTC, jtsiomb commented on README.md
> +
I'm glad we no longer need special destroy instructions for win32. But is it really necessary to spell out that threads need to be created with thrd_create? Surely nobody would expect they should call CreateThread() and then continue with thrd_join afterwards...

2023-01-22 04:59 UTC, jtsiomb commented on README.md
> +```
If this is non-obvious to cmake users, I'd like it in its own subsection... but nevermind I'll reformat this myself.

2023-01-22 14:10 UTC, oold commented
I'll submit the list changes as a separate PR.

2023-01-25 14:30 UTC, jtsiomb commented
I applied the other pull requests, so this needs rebasing to only contain the cmake-specific changes. However I was thinking about how I want to deal with build systems, and I think I want to make them less prominent. I want to emphasize that people can just grab `c11theads.h` (and the source file for windows) and drop it in their projects, and to not be put off by seing an unfamiliar build file and thinking they have to use it.

So what I think I want to do is to move the test out of the way in its own subdirectory, and move the Makefile, plus any other build system you want to add for windows into that directory. That makes it more obvious that the build files are only there to build the test program, and are not required for using the library itself.

From your previous changes in the readme file I take it you meant this not just for building the test program, but as a way of using c11threads in programs which use cmake themselves. I don't like that approach for such a simple library. It feels overcomplicated.

I'll make the change moving test and its build files out of the way later today. If you think there is value having cmake just to build the test program, then please wait a bit, and rebase on top of my change. Ideally I want to see a pull request with just the minimum changes necessary for the cmake build.

2023-01-31 20:13 UTC, oold commented
We can do that, but the CMake solution makes it much easier to build a shared library from the .c file. The shared library is necessary to perform the initialization and deinitialization automatically. I can tell potential users to either somehow figure out how to build a DLL for Windows or to just go with the existing CMake files if that’s alright.

From: John Tsiombikas ***@***.***>
Sent: Wednesday, January 25, 2023 3:31 PM
To: jtsiomb/c11threads ***@***.***>
Cc: Oliver Old ***@***.***>; Author ***@***.***>
Subject: Re: [jtsiomb/c11threads] Add CMake support (PR #23)


I applied the other pull requests, so this needs rebasing to only contain the cmake-specific changes. However I was thinking about how I want to deal with build systems, and I think I want to make them less prominent. I want to emphasize that people can just grab c11theads.h (and the source file for windows) and drop it in their projects, and to not be put off by seing an unfamiliar build file and thinking they have to use it.

So what I think I want to do is to move the test out of the way in its own subdirectory, and move the Makefile, plus any other build system you want to add for windows into that directory. That makes it more obvious that the build files are only there to build the test program, and are not required for using the library itself.

From your previous changes in the readme file I take it you meant this not just for building the test program, but as a way of using c11threads in programs which use cmake themselves. I don't like that approach for such a simple library. It feels overcomplicated.

I'll make the change moving test and its build files out of the way later today. If you think there is value having cmake just to build the test program, then please wait a bit, and rebase on top of my change. Ideally I want to see a pull request with just the minimum changes necessary for the cmake build.

—
Reply to this email directly, view it on GitHub<https://github.com/jtsiomb/c11threads/pull/23#issuecomment-1403711885>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACZ2P3ASB35UQIASGL7OXBLWUE2KHANCNFSM6AAAAAAUCR6IW4>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-02-01 08:13 UTC, jtsiomb commented
I don't want to change this into a standalone separately compiled dll. It's overkill. This is supposed to be a simple "drop it into your code and use it" thing. If someone wants to make a DLL out of it fine, but the supported use case is the drop-in one.

2023-02-07 10:52 UTC, jtsiomb commented
I replaced the visual studio project with an nmake makefile so that it'll work with all visual studio versions, and I think I'll leave it at that for the windows build. I'd rather not add cmake.

2023-02-07 10:52 UTC, closed without merging